### ISSUE TITLE
Error on installing django-debug-toolbar-request-history within make_venv.sh

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#1]
I got error on installing django-debug-toolbar-request-history within make_venv.sh

 Downloading django_debug_toolbar-1.4-py2.py3-none-any.whl (212kB)
Collecting django-debug-toolbar-request-history==0.0.1 (from -r requirements.txt.lock (line 23))
  Could not find a version that satisfies the requirement django-debug-toolbar-request-history==0.0.1 (from -r requirements.txt.lock (line 23)) (from versions: )
No matching distribution found for django-debug-toolbar-request-history==0.0.1 (from -r requirements.txt.lock (line 23))
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management 

Using on Ubuntu 16.04 python 2.7

Commenting out the line in requirements.txt.lock seems to workaround the error and the script make_venv.sh finished.

**Comment by Benzene** [comment]
Oops, that package exists only in our internal repository. I have pushed a commit that removes it from the requirements.txt and requirements.txt.lock.

The rest of the code should work fine. As far as I can tell, this packages wasn't used by default, and it's just a debug helper anyway.

Let us know if you still run into trouble, but if your make_venv.sh has completed, you should be all good to continue.

**Comment by TomasKulhanek** [comment]
Works now. Thank you.
