### ISSUE TITLE
Absolute links in HTML and CSS output not convenient for reverse proxy

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#2]
Absolute links in HTML and CSS output not convenient for reverse proxy.
There are absolute links in HTML and CSS output which seems to be hardcoded in the Python/CSS/HTML code.

This makes moving/accessing the whole VRE application into different web context difficult. 

The web of VRE is now accessible under http://localhost:8000 and it's common use case to aggregate different web apps and balance it via reverse proxy distinguished by context in url e.g. http://localhost/vre

Now I introduced reverse proxy configuration which address this issue using
1. proxying traffic to the local instance of Python web server under the port 8000
2. changing the absolute links within HTML from internal localhost:8000 to externally accessible http://example.com/vre
3. introducing extended parsing to change absolute URL in CSS

However as it introduces some overhead and troubles I propose the following:
A) that all links within generated HTML will be relative - solves 2. and 3.
B) or the VRE could take configuration context - e.g. "/vre" so all links will have this prefix - different solution for 2. and 3. - (no parsing of HTML will be needed)
C) or at least no hard coded absolute links will be in CSS, e.g. "/static/img/favicons/apple-touch-icon-57x57.png" in landing-page.css - (no CSS parsing will be needed)

**Comment by Benzene** [comment]
Most of these can be solved via django configuration, but I haven't tested so.. I must look into things a bit more.

Generally speaking, a lost of the links are already dynamically generated, so it will be mostly a matter of settings the right parameters in the django configuration file. I'll get back to you with the exact details.

**Comment by TomasKulhanek** [comment]
Good. I already tried and found several places to deal with B) as it seems most straightforward and found several.

**Comment by TomasKulhanek** [comment]
VRE in VM is proxied from root, other services proxied with context
