### ISSUE TITLE
constant cpu utilization under no traffic

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#3]
I've noticed constant CPU utilization about 3-10% of the VRE process, even no traffic and no work is done. Cumulatively it works for 21 hours now.

  1  [||||||||||||||||||||||||||||||||||||||||||||   84.1%]   Tasks: 110, 103 thr; 3 running
  2  [||||||||||||                                   21.6%]   Load average: 1.09 0.49 0.27 
  Mem[||||||||||||||||||||||||||||||||||||||||||815M/1.95G]   Uptime: 07:23:17
  Swp[                                               0K/0K]

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 8983 root       20   0  295M 61824     0 S  3.4  3.0 21:02.04 /home/vagrant/VRE-master/.pyvenv/bin/python manage.py runserve

**Comment by Benzene** [comment]
Hi,

the runserver script is meant for development only, not really for production. I will cleanup the documentation on how to run in production.
