### ISSUE TITLE
Create alternative dev.py for local installation

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#6]
Could you please create default local dev.py pointing to sqlite database, so it is installable in custom VM?
Current dev.py points to IP address which is nonsense for WP6 VM. Don't know how to change it to point to sqlite.

**Comment by TomasKulhanek** [comment]
Btw. Is connection to some SQL db still needed if the VRE depends on key-value DB redis?

**Comment by Benzene** [comment]
The SQL database is the main one, used for authentication and the basic stuff. Redis is not very important, it is mainly there for some websockets stuff. But redis uses almost no resources, so no harm in leaving it in.

Anyway, I have added a config that uses sqlite. Just re-run the initialization commands (source rc.sh, python manage.py migrate, honcho start) and you should be running on sqlite.
