### ISSUE TITLE
Dev environment not working

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#7]
Dev environment not working. On latest VRE-master. Following instruction for dev environment, the following is thrown:

[vagrant@localhost VRE-master]$ source rc.sh
(.pyvenv)[vagrant@localhost VRE-master]$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
(.pyvenv)[vagrant@localhost VRE-master]$

**Comment by TomasKulhanek** [comment]
To reproduce in vagrant/virtualbox environment you may follow instruction at
https://github.com/h2020-westlife-eu/wp6-vm
And see within the virtual machine
    vagrant ssh
     cd /home/vagrant/VRE-master 

which is latest master branch copy of git.

**Comment by TomasKulhanek** [comment]
The problem is in psycopg2. Is this package needed?
<code>
Collecting psycopg2==2.6.2 (from -r requirements.txt.lock (line 47))
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zPWfvP/psycopg2/
</code>

**Comment by Benzene** [comment]
psycopg2 is the postgreSQL connector. If you configured with SQLite, it shouldn't be necessary so it's safe to remove it from the requirements.
