### ISSUE TITLE
Javascript loaded from external pages

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/VRE#9]
Just note, I see a lot of javascript dependent packages in source code of VRE, but I find that portal ask to access external libraries also from these addresses: intercom.io, intercomcdn.com, seekscale.com. 

It may not be generally bad practice. But would like to check that all is controlled, whether such dependencies can be satisfied within the west-life domain - included in JS of the server.

**Comment by Benzene** [comment]
Intercom is an analytics service. It is probably only relevant for the public portal, not for the VM so I'll remove it.

The seekscale.com domain belongs to us (Luna). It's an internal domain used for error tracking. But I don't see anywhere where the code loads a library from it. There are API calls that can be made to https://seekscale.com:41002/event but that's all I can see.

**Comment by TomasKulhanek** [comment]
I think seekscale is loaded from the scripts of intercom.
